services:
  - type: web
    name: tastescape-capstone
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: your-username
      - key: DB_PASSWORD
        value: your-password
      - key: DB_NAME
        value: railway
